<!DOCTYPE html>
<html lang="${request.locale_name}">
  <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>VDScrypter - Choose Folder</title>
        <link rel="stylesheet" type="text/css" href="static/css/view.css" media="all">
        <script type="text/javascript" src="static/js/view.js"></script>
  </head>

  <body id="main_body" >

	<img id="top" src="static/images/top.png" alt="">
	<div id="form_container">

		<h1><a>folder_chooser</a></h1>
		<form id="form_842398" class="appnitro"  method="post" action="/folder">
					<div class="form_description">
			<h2>folder_chooser</h2>
			<p>Choose the folder to load.</p>
		</div>
			<ul >

					<li id="li_1" >
		<label class="description" for="folder_path">Path to Images: </label>
		<div>
			<input id="folder_path" name="folder_path" class="element text large" type="text" maxlength="255" value=""/>
		</div><p class="guidelines" id="guide_1"><small>Absolute root path to the images.</small></p>
		</li>		<li id="li_2" >
		<label class="description" for="recurse">Options </label>
		<span>
			<input id="recurse" name="recurse" class="element checkbox" type="checkbox" value="1" />
        <label class="choice" for="recurse">Recurse subfolders</label>

		</span><p class="guidelines" id="guide_2"><small>Optional Parameter to Include.</small></p>
		</li>

					<li class="buttons">
			    <input type="hidden" name="form_id" value="submit_folder" />

				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>
		<div id="footer" style="display: none;">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="static/images/bottom.png" alt="">

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="//oss.maxcdn.com/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//oss.maxcdn.com/libs/twitter-bootstrap/3.0.3/js/bootstrap.min.js"></script>
  </body>
</html>
